name: sms_autofill
description: Flutter plugin to provide SMS code autofill support
version: 2.2.0
homepage: https://github.com/jaumard/sms_autofill

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  pin_input_text_field: ^4.1.1
    #git:
    #  url: https://github.com/TinoGuo/pin_input_text_field
    #  ref: dev
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.jaumard.smsautofill
        pluginClass: SmsAutoFillPlugin
      ios:
        pluginClass: SmsAutoFillPlugin
